apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "currencyservice.fullname" . }}
  labels:
    {{- include "currencyservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "currencyservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "currencyservice.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "currencyservice.serviceAccountName" . }}
      containers:
        - name: currencyservice
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
